"""initial migration

Revision ID: 8a538f36083b
Revises: 
Create Date: 2024-05-28 11:34:28.818696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a538f36083b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outputs_id', table_name='outputs')
    op.drop_table('outputs')
    op.drop_index('ix_wireless_sensors_uid', table_name='wireless_sensors')
    op.drop_table('wireless_sensors')
    op.drop_table('devices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('devices_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='devices_pkey'),
    sa.UniqueConstraint('serial_number', name='devices_serial_number_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('wireless_sensors',
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('humidity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('battery_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rssi', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lastTs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name='wireless_sensors_device_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', name='wireless_sensors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_wireless_sensors_uid', 'wireless_sensors', ['uid'], unique=False)
    op.create_table('outputs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('startTime', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endTime', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lastTime', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wireless_sensor_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['wireless_sensor_uid'], ['wireless_sensors.uid'], name='outputs_wireless_sensor_uid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='outputs_pkey')
    )
    op.create_index('ix_outputs_id', 'outputs', ['id'], unique=False)
    # ### end Alembic commands ###
